
name: Java CI with Maven
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Set up virtual X11
      run: sudo apt-get install xvfb
    - name: Start virtual frame buffer
      run: Xvfb :19 -screen 0 1024x768x16 &
 
    - name: Build with Maven
      #run: mvn --file pom.xml -Pcodecoverage -B package "-Djava.awt.headless=true"  
      run: mvn --file pom.xml -Pcodecoverage -B package "-Djava.awt.headless=true"
      env:
        DISPLAY: :19
        CUCUMBER_PUBLISH_TOKEN: 12345678-1234-1234-1234-123456789123
